module.exports = {
    CONNECT_INFORMATION: 'The connection to the database was successfully',
    UNCONNECT_INFORMATION: 'Unable to connect to the database ',
    SERVER_START: 'Server start on port',
    GET_USERS_ATRIBUTES: ['username', 'email', 'lastLogin', 'status'],
    GET_USERS_ORDER: [['id', 'ASC']],
    STATUS_BLOCK: 'BLOCKED',
    STATUS_ACTIVE: 'ACTIVE',
    EMAIL_ERR_MSG: 'Please correct email test@test.ru',
    USERNAME_ERR_MSG: 'The username must be at least 1 characters',
    NAME_ERR_MSG: 'The name must be at least 1 characters',
    TAGS_ERR_MSG: 'The tags must be at least 1 characters',
    DESCRIPTION_ERR_MSG: 'The description must be at least 1 characters',
    TOPIC_ERR_MSG: 'Invalid topic, please use Books | Signs | Silverware',
    PASSWORD_ERR_MSG: 'The password must be at least 1 characters',
    NAME_MINLENGTH: { min: 1 },
    PASSWORD_MINLENGTH: { min: 1 },
    SALT: 10,
    USER_REGISTER_USED_MSG: 'Sorry, this email has been used!',
    NAME_COLLECTION_USED_MSG: 'Sorry, this name collection has been used!',
    ADD_COLLECTION_CREATE_MSG: 'Collection already exists',
    NAME_ITEM_USED_MSG: 'Sorry, this name item has been used!',
    USER_UNREGISTER_MSG: 'User does not register!',
    PASSWORD_FAILED_MSG: 'Password failed',
    ERROR_UNREG_MSG: 'User Unregister',
    REGISTER_SUCCESS: 'Registration success',
    AUTHORIZATION_SUCCESS: 'Authorization success',
    TIME_TOKEN: '2h',
    UNEXPECTED_ERROR: 'ERROR',
    DELETE_ITEM_MSG: 'Delete this item?',
    DELETE_COLLECTION_MSG: 'Delete this collection?',
    CREATE_COLLECTION_MSG:
        'Collections do not exist. Please create a collection.',
    CREATE_ITEM_MSG: 'Items does not exist. Please create item.',
    LOGOUT_MSG: 'You have been logged out',
    TOPICS: ['Books', 'Signs', 'Silverware'],
    COLLECTION_CREATE_SUCCESS: 'Collection create success',
    ITEM_CREATE_SUCCESS: 'Item create success',
    COLLECTION_DELETE_SUCCESS: 'Collection was delete',
    ITEM_DELETE_SUCCESS: 'Item was delete',
    COLLECTION_UPDATE_SUCCESS: 'Collection was update',
    ITEM_UPDATE_SUCCESS: 'Item was update',
    COLLECTION_NOT_FOUND: 'Collection not found',
    ITEM_NOT_FOUND: 'Item not found',
    COMMENT_NOT_EMPTY: 'Comment not empty',
};
